version: "3.9"
services:
  pt:
    build: .
    ports:
      - 8003:8888
      - 8265:8265
    volumes:
      - .:/workspace
      - ../ray_result:/root/ray_results
    environment:
      - TZ=Asis/Seoul
      - DEBIAN_FRONTEND=noninteractive
    shm_size: "32gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    stdin_open: true
